safe: true
server: true
title: 'Tim's Blog'
exclude: ['LICENSE', 'README.md', 'CNAME']
description: 'A simple Jekyll implementation for personal blogs'
permalink: pretty
url: tlayne.github.io
repository: https://github.com/tlayne/tlayne.github.io
markdown: kramdown