safe: true
server: true
title: 'Tim's Blog'
exclude: ['LICENSE', 'README.md', 'CNAME']
description: 'A simple Jekyll implementation for personal blogs'
permalink: pretty
url: timothysmith.me
markdown: kramdown